### ISSUE TITLE
[Feature Request] Multiple profiles

### ISSUE THREAD

**Issue by AutomateAaron** [voshawn/broadway-lottery#3]
It'd be great to be able to quickly sign up for multiple members or my family without having to reenter the profile data.

**Comment by voshawn** [comment]
Hey @AaronNBrock! That's a cool idea. Unfortunately with other projects I have going on right now, It's unlikely I would be able to get to this soon. 

However, with the winter here, I might be down to see more broadways so happy to reboot this project. 

Any chance you would be down to help by submitting a PR?

**Comment by AutomateAaron** [comment]
@voshawn I'd love to!  I also struggle with many projects, but I'll see what I can do.

Admittedly I've done very little work in with HTML/CSS/JS.  But here's my attack plan:

Edit the `popup.html` "Edit Profile" tab to instead be a placeholder ([like you seem to have done here](https://github.com/voshawn/broadway-lottery/blob/master/popup.html#L24)) with an "Add profile" button that gets read by a click event in the `popup.js` to render a new profile.

My issue, is I'm having some trouble finding how to store data, but I'll deal with that later.

Does this seem like a reasonable way to go about this?

**Comment by voshawn** [comment]
![image](https://user-images.githubusercontent.com/10394260/68151198-da5e2380-ff06-11e9-874e-ad53b66a8039.png)

@AaronNBrock  I think that sounds right. to make it more concrete, I made a rough mock. is this similar to what you're thinking? I'm thinking we could make a dropdown on the profile page to set a profile or add a new profile. 

So let's say you wanted to apply for yourself and then apply for your family. You would first create all the profiles. Then you set one to be active and then apply to the lotteries. Then you would switch profile then apply again. 

In terms of storing data it's pretty simple. I'm just using the `chrome.storage`. See the docs here: 
https://developer.chrome.com/extensions/storage

When we have multiple profiles, it would probably makes sense to change how we are storing a profile and make it an array of profiles instead. Then when we select the active profile, we use the index to populate the data. 

If this sounds good, please dive in! Otherwise let me know if you have any questions!

**Comment by AutomateAaron** [comment]
@voshawn Hmm, the mockup looks nice.  I was thinking more along the lines of just pressing `Enter Selected` once and it'd open tabs for each of the profiles.  For example, if you have 2 profiles and you select 1 show & press `Enter Selected` it would open 2 tabs, both the same show but with different profiles.

**Comment by voshawn** [comment]
Oh yes, that's a better idea! I like that. Let's go in that direction.

**Comment by AutomateAaron** [comment]
One issue I see in the future it if we start dealing with places that require you to have an account (Like luckyseat), it may be difficult to have multiple profiles in this manner.

I.e. It'd need to change sessions for each profile.

**Comment by AaronNBrock** [comment]
One issue I see in the future it if we start dealing with places that require you to have an account (Like luckyseat), it may be difficult to have multiple profiles in this manner.

I.e. It'd need to change sessions for each profile.

**Comment by voshawn** [comment]
I actually wrote some code that does just that! 

https://github.com/voshawn/sessionize-chrome-extension

Check it out haha. Not sure how much of it we can reuse, but it's doable.
